/**
 * Gate Reference Data
 * Human Design gate names and descriptions
 */

export const GATE_NAMES: Record<number, string> = {
  1: 'Self-Expression',
  2: 'The Direction of Self',
  3: 'Ordering',
  4: 'Formulization',
  5: 'Fixed Rhythms',
  6: 'Friction',
  7: 'The Role of the Self',
  8: 'Contribution',
  9: 'Focus',
  10: 'Self-Love',
  11: 'Ideas',
  12: 'Caution',
  13: 'The Listener',
  14: 'Power Skills',
  15: 'Extremes',
  16: 'Skills',
  17: 'Opinions',
  18: 'Correction',
  19: 'Wanting',
  20: 'The Now',
  21: 'The Hunter',
  22: 'Openness',
  23: 'Assimilation',
  24: 'Rationalization',
  25: 'The Spirit of the Self',
  26: 'The Egoist',
  27: 'Caring',
  28: 'The Game Player',
  29: 'Perseverance',
  30: 'Feelings',
  31: 'Influence',
  32: 'Continuity',
  33: 'Privacy',
  34: 'Power',
  35: 'Change',
  36: 'Crisis',
  37: 'Friendship',
  38: 'The Fighter',
  39: 'Provocation',
  40: 'Aloneness',
  41: 'Decrease',
  42: 'Growth',
  43: 'Insight',
  44: 'Coming to Meet',
  45: 'The Gatherer',
  46: 'Determination',
  47: 'Realization',
  48: 'Depth',
  49: 'Principles',
  50: 'Values',
  51: 'Shock',
  52: 'Stillness',
  53: 'Beginnings',
  54: 'Ambition',
  55: 'Spirit',
  56: 'Stimulation',
  57: 'Intuition',
  58: 'Vitality',
  59: 'Sexuality',
  60: 'Limitation',
  61: 'Mystery',
  62: 'Details',
  63: 'Doubt',
  64: 'Confusion',
};

export const GATE_DESCRIPTIONS: Record<number, string> = {
  1: 'The creative force of self-expression. The ability to act as an individual and express unique creativity.',
  2: 'The magnetic drive of receptivity. A natural orientation toward knowing the direction of life.',
  3: 'Innovation through ordering chaos. The energy to bring new forms into existence through mutation.',
  4: 'The logical pressure to find answers. Mental formulation and the need to understand.',
  5: 'Universal patterns and natural rhythms. Waiting for the right timing in life.',
  6: 'Emotional clarity through friction. The gate of conflict that leads to intimacy.',
  7: 'Leadership in the now. The role of pointing the direction for others.',
  8: 'Making a contribution. The expression of individual creativity in the collective.',
  9: 'The power of small. Focusing energy on details to achieve mastery.',
  10: 'Self-love and behavior. The love of self that allows authentic expression.',
  11: 'Peace through ideas. Stimulating ideas that seek expression.',
  12: 'Social caution. The voice that must wait for the right moment to speak.',
  13: 'The listener who remembers. Collecting experiences and stories of others.',
  14: 'Abundance and power skills. The fuel for direction and self-expression.',
  15: 'Love of humanity. The gate of extremes in behavior and flow.',
  16: 'Enthusiasm and skills. Identifying and developing talents through practice.',
  17: 'Following and opinions. The logical mind that organizes patterns.',
  18: 'Correction and judgment. The intuitive drive to improve and perfect.',
  19: 'Wanting and approach. The pressure to be accepted by the tribe.',
  20: 'Contemplation of the now. Being present and aware in the moment.',
  21: 'The hunter and controller. Willpower to control material resources.',
  22: 'Grace and openness. Emotional depth that can move others.',
  23: 'Assimilation and explanation. Translating insights for others to understand.',
  24: 'Return and rationalization. The mental process of revisiting thoughts.',
  25: 'Innocence and the spirit of self. Unconditional love of existence.',
  26: 'The egoist and trickster. Willpower in service of the tribe.',
  27: 'Caring and nourishment. The drive to care for and nurture others.',
  28: 'The game player. Taking risks in pursuit of meaning and purpose.',
  29: 'Saying yes and perseverance. Commitment and follow-through.',
  30: 'Recognition of feelings. Emotional desire for new experiences.',
  31: 'The leader and influence. Democratic leadership through example.',
  32: 'Continuity and transformation. Recognizing what will endure.',
  33: 'Privacy and retreat. The need to process and reflect before sharing.',
  34: 'Pure power and strength. Sacral energy for powerful action.',
  35: 'Change and progress. Seeking new experiences for growth.',
  36: 'Crisis and inexperience. Learning through emotional challenges.',
  37: 'Friendship and community. Creating harmony within the family or group.',
  38: 'The fighter and opposition. Struggling for individual purpose.',
  39: 'The provocateur. Stirring emotions to find spirit.',
  40: 'Aloneness and rest. The need for solitude to restore will.',
  41: 'Fantasy and new beginnings. The pressure to start new experiences.',
  42: 'Growth and maturation. Bringing things to completion.',
  43: 'Insight and breakthrough. Unique mental perspective and knowing.',
  44: 'Coming to meet. Instinctive recognition of patterns.',
  45: 'The gatherer and ruler. Natural leadership of resources.',
  46: 'Determination and love of body. Being in the right place.',
  47: 'Realization and oppression. Making sense of abstract concepts.',
  48: 'Depth and the well. Deep knowledge waiting to be tapped.',
  49: 'Principles and revolution. Emotional sensitivity to justice.',
  50: 'Values and responsibility. Establishing and maintaining order.',
  51: 'Shock and initiation. Competitive spirit and awakening.',
  52: 'Stillness and inaction. The energy to be still and focus.',
  53: 'Beginnings and development. The pressure to start cycles.',
  54: 'Ambition and drive. The fuel for material advancement.',
  55: 'Spirit and abundance. Emotional range from melancholy to ecstasy.',
  56: 'Stimulation and the wanderer. Seeking stimulating experiences.',
  57: 'Intuitive clarity. The penetrating awareness of the now.',
  58: 'Vitality and joy. The energy for improvement and aliveness.',
  59: 'Sexuality and intimacy. Breaking down barriers for connection.',
  60: 'Limitation and acceptance. Accepting limitations as a gateway.',
  61: 'Inner truth and mystery. Pressure to know the unknowable.',
  62: 'Detail and expression. Expressing concepts with precision.',
  63: 'Doubt and questioning. The pressure to question and verify.',
  64: 'Confusion and completion. Mental pressure to make sense of life.',
};
